# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0a23ab832fce22c8d3aa801a5828568d6f724478e7058240e934377c916f95d6ff119742e2d15be0fac750fc9707ef17cbd16dc504696197dfc881459a93f5e

test:
  secret_key_base: 14af24c9e982f59e571d9abb7425e9627c1a764bfcef53b6d8b30b71de95131aeee46842b4e98c8088bc7fb1da9144fe029c83a0871440f5e6e8da35f6280315

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
